CloudDermos/src/com/cloud/entity/Sta_staffinfo.java
package  com.cloud.entity;

public class Sta_staffinfo {
	//员工编号
	private int  sta_id;
	//员工名称
	private String sta_name;
	//员工性别
	private String sta_sex;
	//员工出生年月
	private String sta_birthday;
	//员工电话号码
	private String sta_phone;
	//员工登录名
	private String sta_login;
	//员工登录密码
	private String sta_pwd;
	//员工入职时间
	private String sta_entrytime;
	//员工职位
	private PostInfoEntry post;
	//员工住址
	private String sta_present;
	//员工民族
	private String S_natio;
	//员工籍贯
	private String S_place;
	//员工血型
	private String S_blood;
	//员工身份证号
	private String S_idcate;
	//婚姻状况
	private String S_marital;
	//员工政治面貌
	private String S_politics;
	//最高学历
	private String S_maxeducation;
	//最高学位
	private String S_maxdegree;
	//邮箱
	private String S_Email;
	//紧急联系人的电话
	private String S_emIP;
	//外语等级
	private String S_Englist;
	//计算机等级
	private String S_computer;
	//员工照片
	private String S_img;
	public Sta_staffinfo(int staId, String staName, String staSex,
			String staBirthday, String staPhone, String staLogin,
			String staPwd, String staEntrytime, PostInfoEntry post,
			String staPresent, String sNatio, String sPlace, String sBlood,
			String sIdcate, String sMarital, String sPolitics,
			String sMaxeducation, String sMaxdegree, String sEmail,
			String sEmIP, String sEnglist, String sComputer, String sImg) {
		super();
		sta_id = staId;
		sta_name = staName;
		sta_sex = staSex;
		sta_birthday = staBirthday;
		sta_phone = staPhone;
		sta_login = staLogin;
		sta_pwd = staPwd;
		sta_entrytime = staEntrytime;
		this.post = post;
		sta_present = staPresent;
		S_natio = sNatio;
		S_place = sPlace;
		S_blood = sBlood;
		S_idcate = sIdcate;
		S_marital = sMarital;
		S_politics = sPolitics;
		S_maxeducation = sMaxeducation;
		S_maxdegree = sMaxdegree;
		S_Email = sEmail;
		S_emIP = sEmIP;
		S_Englist = sEnglist;
		S_computer = sComputer;
		S_img = sImg;
	}
	
	public Sta_staffinfo(int staId, String staName) {
		super();
		sta_id = staId;
		sta_name = staName;
	}

	public Sta_staffinfo() {
		super();
	}
	public int getSta_id() {
		return sta_id;
	}
	public void setSta_id(int staId) {
		sta_id = staId;
	}
	public String getSta_name() {
		return sta_name;
	}
	public void setSta_name(String staName) {
		sta_name = staName;
	}
	public String getSta_sex() {
		return sta_sex;
	}
	public void setSta_sex(String staSex) {
		sta_sex = staSex;
	}
	public String getSta_birthday() {
		return sta_birthday;
	}
	public void setSta_birthday(String staBirthday) {
		sta_birthday = staBirthday;
	}
	public String getSta_phone() {
		return sta_phone;
	}
	public void setSta_phone(String staPhone) {
		sta_phone = staPhone;
	}
	public String getSta_login() {
		return sta_login;
	}
	public void setSta_login(String staLogin) {
		sta_login = staLogin;
	}
	public String getSta_pwd() {
		return sta_pwd;
	}
	public void setSta_pwd(String staPwd) {
		sta_pwd = staPwd;
	}
	public String getSta_entrytime() {
		return sta_entrytime;
	}
	public void setSta_entrytime(String staEntrytime) {
		sta_entrytime = staEntrytime;
	}
	public PostInfoEntry getPost() {
		return post;
	}
	public void setPost(PostInfoEntry post) {
		this.post = post;
	}
	public String getSta_present() {
		return sta_present;
	}
	public void setSta_present(String staPresent) {
		sta_present = staPresent;
	}
	public String getS_natio() {
		return S_natio;
	}
	public void setS_natio(String sNatio) {
		S_natio = sNatio;
	}
	public String getS_place() {
		return S_place;
	}
	public void setS_place(String sPlace) {
		S_place = sPlace;
	}
	public String getS_blood() {
		return S_blood;
	}
	public void setS_blood(String sBlood) {
		S_blood = sBlood;
	}
	public String getS_idcate() {
		return S_idcate;
	}
	public void setS_idcate(String sIdcate) {
		S_idcate = sIdcate;
	}
	public String getS_marital() {
		return S_marital;
	}
	public void setS_marital(String sMarital) {
		S_marital = sMarital;
	}
	public String getS_politics() {
		return S_politics;
	}
	public void setS_politics(String sPolitics) {
		S_politics = sPolitics;
	}
	public String getS_maxeducation() {
		return S_maxeducation;
	}
	public void setS_maxeducation(String sMaxeducation) {
		S_maxeducation = sMaxeducation;
	}
	public String getS_maxdegree() {
		return S_maxdegree;
	}
	public void setS_maxdegree(String sMaxdegree) {
		S_maxdegree = sMaxdegree;
	}
	public String getS_Email() {
		return S_Email;
	}
	public void setS_Email(String sEmail) {
		S_Email = sEmail;
	}
	public String getS_emIP() {
		return S_emIP;
	}
	public void setS_emIP(String sEmIP) {
		S_emIP = sEmIP;
	}
	public String getS_Englist() {
		return S_Englist;
	}
	public void setS_Englist(String sEnglist) {
		S_Englist = sEnglist;
	}
	public String getS_computer() {
		return S_computer;
	}
	public void setS_computer(String sComputer) {
		S_computer = sComputer;
	}
	public String getS_img() {
		return S_img;
	}
	public void setS_img(String sImg) {
		S_img = sImg;
	}
	
	
	
}

CloudDermos/src/com/cloud/servlet/staffinfoServlet.java
package com.cloud.servlet;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.cloud.dao.AdminDao;
import com.cloud.entity.BranchEntry;
import com.cloud.entity.PostInfoEntry;
import com.cloud.entity.Sta_staffinfo;
import com.cloud.util.Cmd5;
import com.google.gson.Gson;

public class staffinfoServlet extends HttpServlet {

	 AdminDao da=new AdminDao();
	public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {

	 doPost(request, response);
	}

	 
	public void doPost(HttpServletRequest request, HttpServletResponse response)throws ServletException, IOException {
		//处理乱码
		request.setCharacterEncoding("utf-8");
		response.setCharacterEncoding("utf-8");
		//获取op
		String op=request.getParameter("op");
		
		if("breach".equals(op)){
			//部门查询
			System.out.println("op"+op);
			selectbreach(request, response);
		}else if("addbreach".equals(op)){
			//部门添加
			System.out.println("op"+op);
			addbreach(request, response);
		}else if("updatebreachs".equals(op)){
			//部门修改
			System.out.println("op"+op);
			updatebreachs(request, response);
			
		}else if("deletebrach".equals(op)){
			//部门删除
			System.out.println("op"+op);
			deletebrach(request, response);
			
		}else if("post".equals(op)){
			//职位查询
			System.out.println("op"+op);
			selectpost(request, response);
		}else if("saddpost".equals(op)){
			//添加职位时进行部门的查询方便添加与修改
			request.setCharacterEncoding("utf-8");
			response.setCharacterEncoding("utf-8");
			 List<BranchEntry> list = da.selectbranchs();
			 Gson g=new Gson();
			 String gsonString=g.toJson(list);
			 response.getWriter().print(gsonString);
			System.out.println("你好还哦"+gsonString);
			
		}else if("addpost".equals(op)){
			//职位添加
			System.out.println("op"+op);
			addpost(request, response);
		}else if("deletepost".equals(op)){
			//职位删除
			System.out.println("op"+op);
			deletepost(request, response);
		}else if("updatepost".equals(op)){
			updatepost(request, response);
		}else if("Staffinfo".equals(op)){
			Staffinfo(request, response);
		}
		else if("deletestaffinfo".equals(op)){
			deletestaffinfo(request, response);
		}else if("addStaff".equals(op)){
			addStaff(request, response);
		}else if("postss".equals(op)){
			//部门的查询
			System.out.println("op"+op);
			request.setCharacterEncoding("utf-8");
			response.setCharacterEncoding("utf-8");
			System.out.println("op"+op+"中添加");
			List<PostInfoEntry> plist=da.selectpostss();
			Gson g=new Gson();
			String json=g.toJson(plist);
			response.getWriter().print(json);
			
			
		}else if("updateStaff".equals(op)){
			//部门的查询
			System.out.println("op"+op);
			updateStaff(request, response);
			
		}else if("tianjia".equals(op)){
			//部门的查询
			System.out.println("op"+op);
			int cityId=Integer.parseInt(request.getParameter("cityId"));
			List<PostInfoEntry> daa = da.selectposts(cityId);
			Gson g=new Gson();
			if(daa.size()<1){
				PostInfoEntry pa=new PostInfoEntry(0, "该部门暂无职位", "无");
				daa.add(pa);
				String json=g.toJson(daa);
				response.getWriter().print(json);
			}else{
				String json=g.toJson(daa);
				response.getWriter().print(json);
			}
		}else if("selAAstaffinfo".equals(op)){
			//单个员工查询
			System.out.println("op"+op);
			int id=Integer.parseInt(request.getParameter("id"));
			Sta_staffinfo Sta = da.aaselectstaff(id);
			System.out.println(Sta.getSta_phone());
			request.getSession().setAttribute("Stas", Sta);
		}
		else{
			selectpost(request, response);
			System.out.println("op"+op);
		}
		
	}
	
//=========================员工块==================================================================
	public void updateStaff(HttpServletRequest request, HttpServletResponse response) throws IOException{
		request.setCharacterEncoding("utf-8");
		response.setCharacterEncoding("utf-8");
		//员工编号
		int sta_id=Integer.parseInt(request.getParameter("id"));
		//员工名称
		String sta_name=request.getParameter("S_name");
		//员工性别
		String sta_sex=request.getParameter("S_sex");
		//员工出生年月
		String sta_birthday=request.getParameter("S_birthday");
		//员工电话号码
		String sta_phone=request.getParameter("S_phone");
		//员工登录名
		String sta_login=request.getParameter("S_login");
		//员工登录密码
		String sta_pwd=request.getParameter("S_pwd");
		//员工入职时间
		String sta_entrytime=request.getParameter("S_entrytime");
		//员工职位
		int post=Integer.parseInt(request.getParameter("post"));
		//员工住址
		String sta_present=request.getParameter("S_present");
		//员工民族
		String S_natio=request.getParameter("S_natio");
		//员工籍贯
		String S_place=request.getParameter("S_place");
		//员工血型
		String S_blood=request.getParameter("S_blood");
		//员工身份证号
		String S_idcate=request.getParameter("S_idcate");
		//婚姻状况
		String S_marital=request.getParameter("S_marital");
		//员工政治面貌
		String S_politics=request.getParameter("S_politics");
		//最高学历
		String S_maxeducation=request.getParameter("S_maxeducation");
		//最高学位
		String S_maxdegree=request.getParameter("S_maxdegree");
		//邮箱
		String S_Email=request.getParameter("S_Email");
		//紧急联系人的电话
		String S_emIP=request.getParameter("S_emIP");
		//外语等级
		String S_Englist=request.getParameter("S_Englist");
		//计算机等级
		String S_computer=request.getParameter("S_computer");
		//员工照片
		//String S_img=request.getParameter("S_img");
		//员工必填
		PostInfoEntry ph=new PostInfoEntry();
		
		Sta_staffinfo st=new Sta_staffinfo(sta_id, sta_name, sta_sex, sta_birthday, sta_phone, sta_login, sta_pwd, sta_entrytime, ph, sta_present, S_natio, S_place, S_blood, S_idcate, S_marital, S_politics, S_maxeducation, S_maxdegree, S_Email, S_emIP, S_Englist, S_computer,"a");
		
		int i = da.updateStaff(st, post);
		response.getWriter().print(i);
	};
	//员工添加
	public void addStaff(HttpServletRequest request, HttpServletResponse response) throws IOException{
		request.setCharacterEncoding("utf-8");
		response.setCharacterEncoding("utf-8");
		//员工编号
		//int sta_id=Integer.parseInt(request.getParameter("sta_id"));
		//员工名称
		String sta_name=request.getParameter("S_name");
		//员工性别
		String sta_sex=request.getParameter("S_sex");
		//员工出生年月
		String sta_birthday=request.getParameter("S_birthday");
		//员工电话号码
		String sta_phone=request.getParameter("S_phone");
		//员工登录名
		String sta_login=request.getParameter("S_login");
		//员工登录密码
		String sta_pwd1=request.getParameter("S_pwd");
		//加密密码
		Cmd5 cd = new Cmd5();
		String sta_pwd = cd.getMD5String(sta_pwd1);
		//员工入职时间
		String sta_entrytime=request.getParameter("S_entrytime");
		//员工职位
		int post=Integer.parseInt(request.getParameter("post"));
		//员工住址
		String sta_present=request.getParameter("S_present");
		//员工民族
		String S_natio=request.getParameter("S_natio");
		//员工籍贯
		String S_place=request.getParameter("S_place");
		//员工血型
		String S_blood=request.getParameter("S_blood");
		//员工身份证号
		String S_idcate=request.getParameter("S_idcate");
		//婚姻状况
		String S_marital=request.getParameter("S_marital");
		//员工政治面貌
		String S_politics=request.getParameter("S_politics");
		//最高学历
		String S_maxeducation=request.getParameter("S_maxeducation");
		//最高学位
		String S_maxdegree=request.getParameter("S_maxdegree");
		//邮箱
		String S_Email=request.getParameter("S_Email");
		//紧急联系人的电话
		String S_emIP=request.getParameter("S_emIP");
		//外语等级
		String S_Englist=request.getParameter("S_Englist");
		//计算机等级
		String S_computer=request.getParameter("S_computer");
		//员工照片
		String S_img=request.getParameter("S_img");
		//员工必填
		System.out.println(sta_birthday);
		PostInfoEntry ph=new PostInfoEntry();
		
		Sta_staffinfo st=new Sta_staffinfo(0, sta_name, sta_sex, sta_birthday, sta_phone, sta_login, sta_pwd, sta_entrytime, ph, sta_present, S_natio, S_place, S_blood, S_idcate, S_marital, S_politics, S_maxeducation, S_maxdegree, S_Email, S_emIP, S_Englist, S_computer, S_img);
		
		int i = da.addStaff(st, post);
		response.getWriter().print(i);
	};
	//员工删除
	public void deletestaffinfo(HttpServletRequest request, HttpServletResponse response) throws IOException{
		request.setCharacterEncoding("utf-8");
		response.setCharacterEncoding("utf-8");
		
		int id=Integer.parseInt(request.getParameter("id"));
		int i = da.deletestaffinfo(id);
		response.getWriter().print(i);
		
	};
	//员工查询	
	public void Staffinfo(HttpServletRequest request, HttpServletResponse response) throws IOException{
		request.setCharacterEncoding("utf-8");
		response.setCharacterEncoding("utf-8");
		//分页时取到当前页和显示条数
		int currentPage = request.getParameter("page")==null?1:Integer.parseInt(request.getParameter("page"));
		int size = request.getParameter("limit")==null?5:Integer.parseInt(request.getParameter("limit"));
		//获取参数
		String key = request.getParameter("key")==null?"":request.getParameter("key");
		List<Sta_staffinfo> list=da.selectstaff(size,currentPage,key);
		Gson g=new Gson();
		String json=g.toJson(list);
		json="{\"code\":0,\"msg\":\"\",\"count\":"+da.selectstafftiao(key)+",\"data\":"+json+"}";
		response.getWriter().print(json);
		//System.out.println(json);
	};
	//------------------------------以下是职位---------------------------------------------------------------
	public void selectpost(HttpServletRequest request, HttpServletResponse response) throws IOException{
		request.setCharacterEncoding("utf-8");
		response.setCharacterEncoding("utf-8");
		//分页时取到当前页和显示条数
		int currentPage = request.getParameter("page")==null?1:Integer.parseInt(request.getParameter("page"));
		int size = request.getParameter("limit")==null?5:Integer.parseInt(request.getParameter("limit"));
		//获取参数
		String key = request.getParameter("key")==null?"":request.getParameter("key");
		List<PostInfoEntry> list=da.selectpost(size,currentPage,key);
		Gson g=new Gson();
		String json=g.toJson(list);
		json="{\"code\":0,\"msg\":\"\",\"count\":"+da.selectposttiao(key)+",\"data\":"+json+"}";
		response.getWriter().print(json);
		System.out.println(json);
	};

CloudDermos/WebContent/BackgrounPage/page/personnel/Staffinfo.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <base href="<%=basePath%>">
    
    <title>My JSP 'index.jsp' starting page</title>
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
	<meta http-equiv="description" content="This is my page">
	<!--
	<link rel="stylesheet" type="text/css" href="styles.css">
	-->
	<link rel="stylesheet" href="BackgrounPage/page/personnel/layui/css/layui.css" />
	<script type="text/javascript" src="BackgrounPage/page/personnel/layui/layui.js"></script>
	<script type="text/javascript">
		layui.use(['table','layer'],function(){
			//初始化模块
			var table=layui.table,$=layui.$,layer=layui.layer;
			//绑定表格数据
			table.render({
				elem:'#tb',
				url:'servlet/staffinfoServlet?op=Staffinfo',
				method:'post',
				page:true,
				limit:5,
				limits:[5,10,15],
				cols:[[
					{field:'sta_id',title:'编号',width:70,align:'left'},
					{field:'sta_name',title:'员工名称',align:'center'},
					{field:'sta_sex',title:'性别',width:70,align:'center'},
					{field:'sta_birthday',title:'出生年月',align:'center'},
					{field:'sta_phone',title:'联系电话',align:'center'},
					{field:'sta_login',title:'员工登录名',align:'center'},
					{field:'post',title:'职位',templet:'<div>{{d.post.post_name}}</div>',align:'center'},
					{field:'sta_entrytime',title:'职位时间',align:'center'},
					{fixed:'right',title:'操作',toolbar:'#demo',align:'center'}
				]]
			});
			
			//模糊查询
			$("#search").click(function(){
				var keyword=$("input[name=keywords]").val();
				//重载表格数据
				table.reload('tb',
					{
						where:{key:keyword}
					}
				);
			});
			$("#addBtn").click(function(){
				layer.open({
					type:2,
					title:'添加员工',
					content:'BackgrounPage/page/personnel/addstaffinfo.jsp',
					area:['450px','400px'],
					shade:0.5,
					btn:'关闭',
					resize:false, //不允许拉伸
					zIndex:layer.zIndex
				});
			});
			
			
			//监听表格工具栏
			var jsons;
			table.on('tool(show)',function(obj){
				var data=obj.data;
				var layEvent = obj.event; //获得 lay-event 对应的值（也可以是表头的 event 参数对应的值）
				  var tr = obj.tr; //获得当前行 tr 的DOM对象
				if(obj.event=='update'){
				//将一个JavaScript值(对象或者数组)转换为一个 JSON字符串
					json=JSON.stringify(data);
					console.log(json);
					layer.open({
						type:2,
						title:'修改员工的信息',
						content:'BackgrounPage/page/personnel/updatestaff.jsp',
						area:['650px','500px'],
						shade:0.5,
						btn:'关闭',
						resize:false,   //不允许拉伸
						zIndex:layer.zIndex
						})
					
				}
				if(obj.event=='select'){
				//将一个JavaScript值(对象或者数组)转换为一个 JSON字符串
					$.post("servlet/staffinfoServlet",{op:'selAAstaffinfo',id:data.sta_id})
					json=JSON.stringify(data);
					console.log(json);
					layer.open({
						type:2,
						title:'员工的信息',
						content:'BackgrounPage/page/personnel/Staffinfoss.jsp',
						area:['610px','480px'],
						shade:0.5,
						btn:'关闭',
						resize:false,   //不允许拉伸
						zIndex:layer.zIndex
						})
					
				}
				if(obj.event=='delete'){
					layer.confirm("是否删除该数据?",function(){
						$.post("servlet/staffinfoServlet",{op:'deletestaffinfo',id:data.sta_id},function(res){
							if(res>0){
								layer.msg("删除成功",{time:2000},function(){
									//刷新表格
									table.reload('tb');
								});
							}else if(res==0){
								layer.msg("没有找到编号为【"+data.b_id+"】的数据",{time:2000});
							}else{
								layer.msg("程序异常,请稍后再试....",{time:2000});
							}
						});
					});
				}
			});
		});
	</script>
  </head>
  <body>
  	<div>
  		<div class="layui-form-item">
  		<blockquote class="layui-elem-quote news_search">
  			<div class="layui-input-inline">
		      <input name="keywords" placeholder="请输入查询条件" autocomplete="off" class="layui-input" />
		    </div>
		    <button class="layui-btn layui-btn-radius" id="search">查询</button>
		    <button class="layui-btn layui-btn-radius layui-btn-warm" id="addBtn">添加</button>
		  </blockquote>
	    	<table id="tb" lay-filter="show"></table>
  		</div>
  	</div>
  	<script type="text/html" id="demo">
		<a class="layui-btn layui-btn-xs" lay-event="select">详情</a>
  		<a class="layui-btn layui-btn-xs" lay-event="update">修改</a>
  		<a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="delete">删除</a>
  	</script>
  </body>
</html>

CloudDermos/WebContent/BackgrounPage/page/personnel/Staffinfoss.jsp
<%@ page language="java" import="java.util.*" pageEncoding="utf-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%
String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>
    <base href="<%=basePath%>">
    
    <title>My JSP 'Staffinfoss.jsp' starting page</title>
    
	<meta http-equiv="pragma" content="no-cache">
	<meta http-equiv="cache-control" content="no-cache">
	<meta http-equiv="expires" content="0">    
	<meta http-equiv="keywords" content="keyword1,keyword2,keyword3">
	<meta http-equiv="description" content="This is my page">
	<!--
	<link rel="stylesheet" type="text/css" href="styles.css">
	-->
	<style type="text/css">
			tr td{
				width: 80px;
				height: 30px;
				text-align: center;
			}
		</style>
	<link rel="stylesheet" type="text/css" href="BackgrounPage/page/personnel/layui/css/layui.css">
  	<script type="text/javascript" src="BackgrounPage/page/personnel/layui/layui.js"></script>
  </head>
 	<body>
		<form action="" >
			<table 	cellpadding="0" cellspacing="0" width="600px" border="1px">
				
				<tr>
					<th>姓名</th>
					<td   id="name">${Stas.sta_name}</td>
					<th>性别</th>
					<td id="sex">${Stas.sta_sex} </td>
					<td colspan="2" rowspan="5" id="sex"><img style="width: 135px;height: 150px" src="BackgrounPage/images/face.jpg"/></td>
				</tr>
				<tr>
					<th>出生年月</th>
					<td  id="S_birthday">${Stas.sta_birthday} </td>
					<th>民族</th>
					<td id="S_natio">${Stas.s_natio}</td>
					
				</tr>
				<tr>
					<th>籍贯</th>
					<td id="S_place">${Stas.s_place} </td>
					<th>血型</th>
					<td  id="S_blood">${Stas.s_blood} </td>
				</tr>
				<tr>
					<th>身份证号</th>
					<td colspan="3" id="S_idcate">${Stas.s_idcate}</td>
				</tr>
				<tr>
					<th>联系电话</th>
					<td colspan="3" id="S_phone">${Stas.sta_phone}</td>
					
				</tr>
				<tr>
					<th>婚姻状况</th>
					<td colspan="2" id="S_marital">${Stas.s_marital} </td>
					<th>政治面貌</th>
					<td colspan="2" id="S_politics">${Stas.s_politics} </td>
					
				</tr>
				<tr>
					<th>最高学历</th>
					<td colspan="5" id="S_maxeducation">${Stas.s_maxeducation} </td>
				</tr>
				<tr>
					<th>最高学位</th>
					<td colspan="5" id="S_maxdegree">${Stas.s_maxdegree} </td>
				</tr>
				<tr>
					<th>居住地址</th>
					<td colspan="5" id="sta_present">${Stas.sta_present}</td>
				</tr>
				<tr>
					<th>E-mail</th>
					<td colspan="5" id="S_Email">${Stas.s_Email}</td>
				</tr>
				<tr>
					<th>紧急联系人</th>
					<td colspan="5" id="S_emIP">${Stas.s_emIP}</td>
				</tr>
				<tr>
					<th>外语等级</th>
					<td colspan="2" id="S_Englist">${Stas.s_Englist}</td>
					<th>计算机等级</th>
					<td colspan="2" id="S_computer">${Stas.s_computer}</td>
				</tr>
			</table>
			
		</form>
	</body>
</html>